version: '3'

services:
  render:
    image: 'gcc:12.2'
    container_name: render
    volumes:
      - ../header:/workspace/header
      - ../image:/workspace/image
      - ../src:/workspace/src
      - ../test:/workspace/test
    working_dir: /workspace
    tty: true
