version: '3'

services:
  render:
    image: 'gcc:12.2'
    container_name: render
    volumes:
      - ../test:/workspace/test
      - ../header:/workspace/header
    working_dir: /workspace
    tty: true
